name: Build FastCRUD CLI and Upload Release Assets

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os == 'windows' && 'windows-latest' || matrix.os == 'macOS' && 'macos-latest' || 'ubuntu-latest' }}

    strategy:
      matrix:
        os: [linux, macOS, windows]

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      #
      # macOS
      #
      - name: Build [macOS]
        if: matrix.os == 'macOS'
        working-directory: cli
        env:
          CLI: fastcrud
          OS: ${{ matrix.os }}
        run: |
          echo "Building macOS amd64..."
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build \
            -ldflags="-s -w -X 'main.version=$(git describe --tags)'" \
            -trimpath -o ../$CLI main.go
          cd ..
          zip -9q $CLI-$OS-amd64.zip $CLI
          rm $CLI
          cd cli

          echo "Building macOS arm64..."
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build \
            -ldflags="-s -w -X 'main.version=$(git describe --tags)'" \
            -trimpath -o ../$CLI main.go
          cd ..
          zip -9q $CLI-$OS-arm64.zip $CLI
          rm $CLI

      #
      # Windows
      #
      - name: Build [Windows]
        if: matrix.os == 'windows'
        working-directory: cli
        env:
          CLI: fastcrud
          OS: ${{ matrix.os }}
        run: |
          echo "Building Windows amd64..."
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build \
            -ldflags="-s -w -X 'main.version=$(git describe --tags)'" \
            -trimpath -o ../$CLI.exe main.go
          cd ..
          zip -9q $CLI-$OS-amd64.zip $CLI.exe
          rm $CLI.exe

      #
      # Linux
      #
      - name: Build [Linux]
        if: matrix.os == 'linux'
        working-directory: cli
        env:
          CLI: fastcrud
          OS: ${{ matrix.os }}
        run: |
          echo "Building Linux amd64..."
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
            -ldflags="-s -w -X 'main.version=$(git describe --tags)'" \
            -trimpath -o ../$CLI main.go
          cd ..
          tar -I 'gzip -9' -cf $CLI-$OS-amd64.tar.gz $CLI
          rm $CLI

      #
      # Upload artifacts
      #
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            fastcrud-macOS-amd64.zip
            fastcrud-macOS-arm64.zip
            fastcrud-windows-amd64.zip
            fastcrud-linux-amd64.tar.gz
